apiVersion: v1
kind: Namespace
metadata:
  name: sonarqube
  namespace: sonarqube

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-db
  namespace: sonarqube
spec:
  storageClassName: local-path
  resources:
    requests:
      storage: 4G
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
  namespace: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      volumes: 
        - name: sonarqube-data
          persistentVolumeClaim:
            claimName: sonarqube-data
        - name: sonarqube-extensions
          persistentVolumeClaim:
            claimName: sonarqube-extensions
        - name: sonarqube-logs
          persistentVolumeClaim:
            claimName: sonarqube-logs
        - name: sonarqube-temp
          persistentVolumeClaim:
            claimName: sonarqube-temp
      containers:
      - name: sonarqube
        image: sonarqube:lts
        ports:
        - containerPort: 9000
        env:
        - name: SONARQUBE_JDBC_URL
          value: "jdbc:postgresql://sonarqube-db:5432/sonar"
        volumeMounts:
        - name: sonarqube-data
          mountPath: /opt/sonarqube/data
        - name: sonarqube-extensions
          mountPath: /opt/sonarqube/extensions
        - name: sonarqube-logs
          mountPath: /opt/sonarqube/logs
        - name: sonarqube-temp
          mountPath: /opt/sonarqube/temp
        resources: {}
      
---
apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  namespace: sonarqube
spec:
  type: NodePort
  selector:
    app: sonarqube
  ports:
    - name: http
      port: 9000
      targetPort: 9000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube-db
  namespace: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube-db
  template:
    metadata:
      labels:
        app: sonarqube-db
    spec:
      volumes: 
        - name: sonarqube-db-data
          persistentVolumeClaim:
            claimName: sonarqube-db
      containers:
      - name: postgres
        image: postgres
        env:
        - name: POSTGRES_USER
          value: sonar
        - name: POSTGRES_PASSWORD
          value: sonar
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: sonarqube-db-data
          mountPath: /var/lib/postgresql/data
        resources: {}
      
---
apiVersion: v1
kind: Service
metadata:
  name: sonarqube-db
  namespace: sonarqube
spec:
  selector:
    app: sonarqube-db
  ports:
    - name: postgres
      port: 5432

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarqube
  namespace: sonarqube
  labels:
    name: sonarqube
spec:
  rules:
  - host: sonarqube.vitorcorreia.me
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: sonarqube
            port: 
              number: 9000
