apiVersion: apps/v1
kind: Deployment
metadata:
  name: seoul-mf
  namespace: microfrontends
spec:
  selector:
    matchLabels:
      app: seoul-mf
  template:
    metadata:
      labels:
        app: seoul-mf
    spec:
      containers:
      - name: seoul-mf
        image: nicolesilva.azurecr.io/seoul-mf:#IMAGE_TAG#
        resources: {}
        ports:
        - name: http
          containerPort: 80
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: nginx-config
      volumes:
      - name: nginx-config  
        configMap:
          name: frontend-nginx-config
          items:
            - key: nginx.conf
              path: nginx.conf        
---

apiVersion: v1
kind: Service
metadata:
  name: seoul-mf
  namespace: microfrontends
spec:
  selector:
    app: seoul-mf
  ports:
  - port: 80
    targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: seoul-mf
  namespace: microfrontends
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      add_header Access-Control-Allow-Origin https://shell.vitorcorreia.me;
spec:
  ingressClassName: nginx
  rules:
  - host: seoul-system.vitorcorreia.me
    http:
      paths:
      - pathType: ImplementationSpecific
        path: "/"
        backend:
          service:
            name: seoul-mf
            port: 
              number: 80
