apiVersion: apps/v1
kind: Deployment
metadata:
  name: shell
  namespace: microfrontends
spec:
  selector:
    matchLabels:
      app: shell
  template:
    metadata:
      labels:
        app: shell
    spec:
      containers:
      - name: shell
        image: nicolesilva.azurecr.io/shell:#IMAGE_TAG#
        resources: {}
        ports:
        - name: http
          containerPort: 80
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: nginx-config
      volumes:
      - name: nginx-config  
        configMap:
          name: frontend-nginx-config
          items:
            - key: nginx.conf
              path: nginx.conf
        
---

apiVersion: v1
kind: Service
metadata:
  name: shell
  namespace: microfrontends
spec:
  selector:
    app: shell
  ports:
  - port: 80
    targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shell
  namespace: microfrontends
spec:
  ingressClassName: nginx
  rules:
  - host: shell.vitorcorreia.me
    http:
      paths:
      - pathType: ImplementationSpecific
        path: "/"
        backend:
          service:
            name: shell
            port: 
              number: 80
